insert into experiencias (titulo, tipo, entidad, descripcion, fecha_inicio, fecha_fin)
    values  ('Programador web', 'Experiencia profesional', 'Excmo. Ayuntamiento de Sanlúcar de Barrameda', 'Análisis y desarrollo de una aplicación web para la gestión de las ayudas sociales y horas extras de los empleados y funcionarios del ayuntamiento. Además de su posterior valoración por parte de la comisión de control. La aplicación generaba automáticamente los informes de cada solicitud y cada valoración.
                Para la realización de esta aplicación se usaron las siguientes tecnologías: PHP, Yii2 Framework, JavaScript, HTML5, CSS3, Bootstrap, SQL, PostgreSQL, AJAX, Git, GitLab, GitHub, jQuery, Linux Ubuntu, Windows', '2017-03-01', '2017-06-30'),
            ('Diseñador de páginas web', 'Experiencia profesional', 'Excmo. Ayuntamiento de Sanlúcar de Barrameda', 'Diseño y mantenimiento web. Usando las tecnologías: HTML5, CSS3, JavaScript y Adobe Dreamweaver CS6', '2014-01-21', '2014-07-21'),
            ('Técnico de Prevención de Riesgos Laborales', 'Experiencia profesional', 'Consultoría Prevención del Sur', 'Realización de evaluaciones de riesgos y planes de prevención a empresas de diferentes sectores.', '2011-03-01', '2011-06-30'),
            ('C.F.G.S. Desarrollo de aplicaciones web', 'Formación académica', 'IES Doñana', 'Ciclo Formativo de Grado Superior', '2015-09-15', '2017-06-30'),
            ('C.F.G.S. Prevención de Riesgos Profesionales', 'Formación académica', 'IES Doñana', 'Ciclo Formativo de Grado Superior', '2009-09-15', '2011-06-30'),
            ('Bachillerato', 'Formación académica', 'IES Francisco Pacheco', 'Modalidad de Ciencias Sociales', '2007-09-15', '2009-06-30'),
            ('Curso Desarrollo Web', 'Formación complementaria', 'Certificado por Google y Universidad de Alicante', 'Curso de desarrollo web certificado por Google y la Universidad de Alicante. En el que se impartieron los siguientes modulos: Historia web, Funcionamiento, Escritura web, Publicación, Web correcta, Presentación web, Elementos web, Maqueta web, Exito web y Proximos pasos', '2017-12-01', '2017-12-30'),
            ('C.O. INFONOVA Diseño y mantenimiento de páginas web', 'Formación complementaria', 'Excmo. Ayuntamiento de Sanlúcar de Barrameda', 'Curso de 1920 horas certificado por el Ayuntamiento de Sanlúcar de Barrameda.', '2013-07-21', '2014-07-21');
